### ISSUE TITLE
compare_predictions function does not work (vignette related)

### ISSUE THREAD

**Issue by PCK1992** [benjamin-w-campbell/fergm#1]
I followed the vignette and tried comparing the fergm and ergm fit. I get the following error:

`> predict_out <- compare_predictions(ergm_fit = ergm.fit, fergm_fit = fergm.fit, replications = 100)
Error in compare_predictions(ergm_fit = ergm.fit, fergm_fit = fergm.fit,  : unused arguments (ergm_fit = ergm.fit, fergm_fit = fergm.fit)`

**Comment by benjamin-w-campbell** [comment]
Thanks for reaching out, @PCK1992!  I have begun looking into the source of this error and should have an answer and solution within the hour.

Thanks for bringing this to my attention.

**Comment by benjamin-w-campbell** [comment]
In the prior version of the package I changed the argument naming for some functions, `compare_predictions()` was one of these functions.  Specifically, I changed the name of two arguments: `ergm_fit` and `fergm_fit` to `ergm.fit` and `fergm.fit`.  I did this to ensure consistency throughout the package between argument names and in the cases of examples, their corresponding test object names.  It appears that I failed to update this function call in the vignette. 

If you use the following code in its place, you should find that it works: 
`predict_out <- compare_predictions(ergm.fit = ergm.fit, fergm.fit = fergm.fit, replications = 100)`

In the next little bit I will push an updated version of the package and the vignette to this repository.  I also plan to submit an updated version to CRAN by the end of the day.  

Thanks again for bringing this to my attention, please let me know if you have any additional questions.  Thanks for using the `fergm` package!

**Comment by benjamin-w-campbell** [comment]
Closing this as it has been troubleshooted.  Not so much a bug as an uncorrected typo in the Vignette.
